apiVersion: v1
data:
  version: alpine
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-version
  namespace: demo
data:
  {{- range $key, $val := .Values.configMap }}
  {{ $key }}: {{ $val }}
  {{- end}}
