apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-version
  namespace: {{.Values.namespace.name}}
data:
  {{- range $key, $val := .Values.configMap }}
  {{ $key }}: {{ $val }}
  {{- end}}
