apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
    tag: alpine
  name: nginx-alpine
  namespace: {{.Values.namespace.name}}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-alpine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-alpine
    spec:
      containers:
      - image: {{.Values.image.repository}}:{{.Values.image.tag}}
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: nginx
        resources:
          requests:
            cpu: {{.Values.resources.cpu}}
            memory: {{.Values.resources.memory}}
status: {}
