apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-alpine
    tag: alpine
  name: nginx-alpine
  namespace: {{.Values.namespace.name}}
spec:
  type: {{.Values.service.type}}
  ports:
  - port: {{.Values.service.port}}
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx-alpine
status:
  loadBalancer: {}
